### ISSUE TITLE
Parse Dashboard Not Loading

### ISSUE THREAD

**Issue by akereachu** [fluxscape/fluxscape#39]
After having this issue: https://github.com/fluxscape/fluxscape/issues/37
I did succeed by using VPN to complete the lessons. After creating the Task Manager App
With the VPN back on, I'm experiencing another issue with the Cloud Services.
The Parse Dashboard Does not load.

Please Note: I followed this tutorial: https://www.youtube.com/watch?v=ecas2QPbr0g

![Screen Shot 2024-06-16 at 3 22 05 PM](https://github.com/fluxscape/fluxscape/assets/62541622/ed0baeb2-cd05-4499-9484-f612cb51ca4c)

**Comment by erictuvesson** [comment]
This happens when Parse Dashboard fails to connect to the Cloud Service. Make sure the App Id, Master key and endpoint is correct in the Cloud Service settings.

**Comment by alan-x-n** [comment]
Very strange, I'm not able to reproduce any of these issues.

**Comment by akereachu** [comment]
@erictuvesson @alan-x-n   Okay, Please check out my demo settings and guide me on how to do it correctly.
Following this guide https://www.youtube.com/watch?v=ecas2QPbr0g, they didn't have some additional inputs found on  the current version

![Screen Shot 2024-06-16 at 8 35 27 PM](https://github.com/fluxscape/fluxscape/assets/62541622/baf00c73-848a-4f70-bc72-eb292b9ee36c)

**Comment by alan-x-n** [comment]
Just FYI, you probably never want to expose your cloud service credentials publicly.

Your endpoint is wrong, im also wondering where you got these information from, as I don't see it specified in the video, but I could have missed it.

Either way, you should be following this
https://docs.fluxscape.io/docs/getting-started/quick-setup/

Also it's appearing these issues are unrelated to the project source code itself, and more like product support questions. 

We have a great community for that! You can join the discord here https://discord.com/invite/fXNW9EXa6A

**Comment by akereachu** [comment]
@alan-x-n thank you, those credentials where demo credentials. no security risk. just trying to access the Local database without an actual live cloud server.

**Comment by alan-x-n** [comment]
> @alan-x-n thank you, those credentials where demo credentials. no security risk. just trying to access the Local database without an actual live cloud server as seen in the tutorial. I will try to follow the tutorial you sent. thank you

There is no local database, unless you're doing a more complicated setup of a docker and running the cloud service yourself, but that's a whole other thing and tutorial completely.

If there's anything else, around this topic ping us on Discord :) 

https://discord.com/invite/fXNW9EXa6A

**Comment by akereachu** [comment]
@alan-x-n  i hoping to see something like this locally to test the app before hosting.

![Uploading Screen Shot 2024-06-16 at 10.12.59 PM.jpg…]()
